### ISSUE TITLE
Copyright claim.

### ISSUE THREAD

**Issue by Solistra** [HimeWorks/RM_RubyParser#1]
Somehow, you managed to violate the MIT license -- which is not easy.

In this particular case, you actually place this repository under the MIT license with yourself as the copyright holder without giving any indication that the _entirety_ of the work herein was actually performed by the `parser` library as written by @whitequark. What you can claim copyright for is, essentially, the test code and adding a few constants to `Encoding`.

**Comment by whitequark** [comment]
:+1: I'd like to see this fixed

**Comment by Solistra** [comment]
Just noticed that this repository also distributes portions of the `slop` command-line option parser as written by @leejarvis (I'm assuming so that you could get `parser` to work), also licensed under the MIT license without proper adherence.

**Comment by leejarvis** [comment]
:+1: Please fix this

**Comment by HimeWorks** [comment]
Hi all,

I have updated the license with the projects that have been included in the distribution.
Please review it and determine whether it is suitable.

Thanks.

**Comment by Solistra** [comment]
I can't speak for either of the authors who wrote the libraries that you packaged and distributed, but I still don't understand what you're applying your own copyright claim to. Is it this?

```ruby
$LOAD_PATH.unshift("System") unless $LOAD_PATH.include?("System")

# RM doesn't include these constants?
class Encoding
  BINARY = "ASCII-8BIT"
  UTF_8 = "utf-8"
  UTF_16LE = "utf-16le"
end

require 'parser/current'
p Parser::CurrentRuby.parse($RGSS_SCRIPTS[-2][3])
```

**Comment by HimeWorks** [comment]
Yes.

Are you concerned whether I am claiming the RPG Maker binaries as my own?

**Comment by Solistra** [comment]
No -- I'm concerned that you're claiming copyright for defining a few constants, appending to the load path, and requiring an external library that actually does everything.

**Comment by HimeWorks** [comment]
What alternatives do you suggest?

**Comment by Solistra** [comment]
...really? I'm not a lawyer, but what you provided is so trivial that I can't imagine that you can even claim _any_ kind of copyright for it. Both @whitequark and @leejarvis licensed the work, copyrighted it, and earned it (and yes, I just added those mentions to get their input as well).

By the way, I hope you two don't mind the extra mentions, but am I missing something here? What would _you_ two consider the appropriate action / how would you consider the issue fixed? Is it fixed already?

**Comment by whitequark** [comment]
@Solistra 
>No -- I'm concerned that you're claiming copyright for defining a few constants, appending to the load path, and requiring an external library that actually does everything.

I think that's OK. In my view there is no issue anymore.

**Comment by Solistra** [comment]
@whitequark Thank you for your input, I really appreciate it. :)

**Comment by leejarvis** [comment]
Yes I think it's OK now too. @Solistra thank you for bringing this to attention, much appreciated. Thank you @HimeWorks for the quick fix.
